folio-org/mod-login-saml

ramls/saml-login.raml

Add missing colon.
raml-cop said: ERROR Property 'body' can not have scalar value

Fix RAML content-type declaration

---

ramls/saml-login.raml

This is broke the source generation with NPE
```
java.lang.NullPointerException
at org.raml.jaxrs.codegen.core.AbstractGenerator.hasAMultiTypeFormParameter(AbstractGenerator.java:452)
at org.raml.jaxrs.codegen.core.AbstractGenerator.addFormParameters(AbstractGenerator.java:470)
at org.raml.jaxrs.codegen.core.AbstractGenerator.addBodyParameters(AbstractGenerator.java:535)
at org.raml.jaxrs.codegen.core.Generator.addResourceMethod(Generator.java:189)
at org.raml.jaxrs.codegen.core.AbstractGenerator.addResourceMethods(AbstractGenerator.java:724)
at org.raml.jaxrs.codegen.core.AbstractGenerator.addResourceMethods(AbstractGenerator.java:292)
at org.raml.jaxrs.codegen.core.AbstractGenerator.addResourceMethods(AbstractGenerator.java:303)
at …
```

Revert "Fix RAML content-type declaration"

---

pom.xml

Hi Robert, I think I found out why the strange java.lang.NullPointerException at org.opensaml.saml.metadata.resolver.impl.DOMMetadataResolver.initMetadataResolver(DOMMetadataResolver.java:68) . Thanks.

Avoid same name property files overwritten (MODLOGSAML-18)

---

descriptors/ModuleDescriptor-template.json

Add "requires" section to module descriptor for required interfaces.

---

Dockerfile
descriptors/ModuleDescriptor-template.json

Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).

MODLOGSAML-53 FOLIO-2358 manage container memory

---

descriptors/ModuleDescriptor-template.json

Since `permissionsRequired` is now a required property in the module descriptor for each endpoint, we need to add it in a few places.
This is a breaking change since we're adding permission requirements where they didn't exist before, hence the major interface version change.
See [MODLOGSAML-60](https://issues.folio.org/browse/MODLOGSAML-60)

MODLOGSAML-60 - Add missing permissionsRequired

---

NEWS.md
pom.xml

Release v2.0.0.
The major version bump is due to new permission requirements on APIs which were previously unrestricted.
See:  https://issues.folio.org/browse/MODLOGSAML-62

MODLOGSAML-62 - Release v2.0.0

---

pom.xml

We need to bump the rest-assured version otherwise it
introduces an old incompatible jopt-simple version.

MODLOGSAML-73: Upgrade raml-module-builder (RMB) to 30.2.6

---

NEWS.md
pom.xml

* [MODLOGSAML-73](https://issues.folio.org/browse/MODLOGSAML-73) Upgrade raml-module-builder (RMB) from 30.0.1 to 30.2.6

MODLOGSAML-74: Release 2.0.1

---

pom.xml
src/main/java/org/folio/config/JsonReponseSaml2RedirectActionBuilder.java
src/main/java/org/folio/config/SamlClientLoader.java
src/main/java/org/folio/config/model/SAML2ClientMock.java
src/main/java/org/folio/rest/impl/SamlAPI.java
src/main/java/org/folio/util/HttpActionMapper.java
src/main/java/org/folio/util/VertxUtils.java
src/test/java/org/folio/config/JsonReponseSaml2RedirectActionBuilderTest.java
src/test/java/org/folio/rest/impl/SamlAPITest.java
src/test/java/org/folio/util/VertxUtilsTest.java

pac4j-saml 3.8.3 depends on cryptacular 1.2.3 that has this
denial of service security vulnerability:
* CiphertextHeader.java in Cryptacular 1.2.3 allows attackers to trigger
excessive memory allocation during a decode operation, because the nonce
array length associated with "new byte" may depend on untrusted input
within the header of encoded data.
https://nvd.nist.gov/vuln/detail/CVE-2020-7226
Upgrading to pac4j-saml-opensamlv3:jar:4.1.0 will use the fixed version
cryptacular 1.2.4.
Also bump the other dependencies:
RMB from 30.2.6 to 30.2.9.
Vert.x from to 3.9.2 to 3.9.4.
pac4j from 3.8.3 to 4.1.0.
vertx-pac4j from 4.1.1 to 5.0.0.
JUnit from 4.12 to 4.13.1 to fix another security vulnerability:
https://nvd.nist.gov/vuln/detail/CVE-2020-15250
A few code changes are needed, see pac4j …

MODLOGSAML-67: pac4j-saml 4.1.0, Cryptacular 1.2.4 (CVE-2020-7226)

---

src/main/java/org/folio/util/UrlUtil.java
src/test/java/org/folio/util/UrlUtilTest.java

Running UrlUtilTest with German locale fails:
java.lang.AssertionError: Not equals : Connection refused: localhost/127.0.0.1:51477 != Verbindungsaufbau abgelehnt: localhost/127.0.0.1:51477
at org.folio.util.UrlUtilTest.lambda$checkIdpUrlNon200$1(UrlUtilTest.java:62)
Change UrlUtil and UrlUtilTest for locale independence.
Futurise UrlUtil.checkIdpUrl.

Make UrlUtilTest locale independent 

---

descriptors/ModuleDescriptor-template.json
ramls/saml-login.raml
src/main/java/org/folio/rest/impl/SamlAPI.java
src/test/java/org/folio/rest/impl/SamlAPITest.java

Please https://issues.folio.org/browse/MODLOGSAML-63. The basic idea is to generate a random id and store in the cookie. Later then compare the value during /callback call. There is a detailed explanation in @craigmcnally's original [PR](https://github.com/folio-org/mod-login-saml/pull/63). I simplified the implementation. Hopefully it did not lower the security requirement.

MODLOGSAML-63 Implement CSRF Prevention

---

src/main/java/org/folio/rest/impl/SamlAPI.java
src/test/java/org/folio/rest/impl/SamlAPITest.java

Please see https://issues.folio.org/browse/MODLOGSAML-58. This PR basically leveraged the same cookie approach used for CSRF detection. Expanded the cookie value to include the relay url as well. By doing so the SAML response redirection url will have to match the original requester one.

MODLOGSAML-58 Arbitrary URL Redirection in SAML Response

---

pom.xml

mod-login-saml has these dependencies:
* xerces:xmlParserAPIs:2.6.2 via domain-models-runtime
* xml-apis: xml-apis:1.3.04 via pac4j-saml-opensamlv3
Both libraries haven been included into JDK since Java 9.
Using any of these classes (org.w3c.dom.**) causes this
compile error in Java compilers that comply with the Java specs
(for example the one used by Eclipse):
`The package org.w3c.dom is accessible from more than one module: <unnamed>, java.xml`
Solution:
Exclude these dependencies.

MODLOGSAML-102: Remove xerces:xmlParserAPIs and xml-apis dependencies

---

pom.xml

The Netty upgrade fixes HTTP request header smuggling: https://nvd.nist.gov/vuln/detail/CVE-2021-43797
Netty is indirectly upgraded via Vert.x upgrade.
Log4j is indirectly upgraded via RMB upgrade.

MODLOGSAML-129: Netty 4.1.72, Log4j 2.17.0, Vert.x 4.2.3, RMB 33.2.3

---

pom.xml
src/main/java/org/folio/config/ConfigurationsClient.java
src/main/java/org/folio/config/JsonReponseSaml2RedirectActionBuilder.java
src/main/java/org/folio/rest/impl/ApiInitializer.java
src/main/java/org/folio/util/UrlUtil.java
src/main/java/org/folio/util/WebClientFactory.java
src/test/java/org/folio/rest/impl/IdpTest.java
src/test/java/org/folio/rest/tools/utils/ModuleName.java
src/test/java/org/folio/util/UrlUtilTest.java

Update RMB from 33.2.5 to 33.2.7.
Update Vert.x from 4.2.4 to 4.2.5.
Add log4j-slf4j-impl to also get slf4j log messages (via log4j).
Dump variables when getRedirectionAction has an exception.
Use WebClientFactory from okapi-common.
For web client increase connect timeout and idle timeout
from 5 seconds to 15 seconds, and enable keep alive.

MODLOGSAML-107: slf4j, web client timeout 15s

---

src/main/java/org/folio/config/JsonReponseSaml2RedirectActionBuilder.java
src/main/java/org/folio/rest/impl/SamlAPI.java
src/main/java/org/folio/util/DumpUtil.java
src/test/java/org/folio/rest/impl/SamlAPITest.java
src/test/java/org/folio/util/DumpUtilTest.java
src/test/java/org/folio/util/MockJson.java
src/test/resources/mock_metadata_bogus.json

Remove the Saml2Client (the configuration) from SamlConfigHolder
(the configuration cache) if there is an internal error that
might be caused by a bogus configuration.
The issue can be reproduced with an IdP metadata XML with
entityID set to an empty string.
To see the actual cause the IdP metadata will be logged on
internal error.

MODLOGSAML-107: Delete configuration cache on internal error

---

pom.xml

Fixing stack overflow DoS https://nvd.nist.gov/vuln/detail/CVE-2020-36518

MODLOGSAML-136: jackson-databind 2.13.2.2 (CVE-2020-36518)

---

src/main/java/org/folio/config/JsonReponseSaml2RedirectActionBuilder.java
src/main/java/org/folio/rest/impl/SamlAPI.java

For https://issues.folio.org/browse/MODLOGSAML-107 debug information was added when an exception occurred. This also contains sensitive values like the okapi token.
Task: Reduce logging and don't log okapi token.

MODLOGSAML-138: Reduce error logging

---

src/main/java/org/folio/util/UrlUtil.java
src/test/java/org/folio/rest/impl/SamlAPITest.java
src/test/java/org/folio/util/UrlUtilTest.java

If `Server: Duo/1.0` header exists allow text/xhtml.
Otherwise require one of the four XML media types.

MODLOGSAML-134: Content-Type validation for Duo's text/xhtml

---

pom.xml
src/main/java/org/folio/config/model/SAML2ClientMock.java
src/test/java/org/folio/util/DumpUtilTest.java

Upgrade RMB from 33.2.7 to 34.0.0.
Upgrade Vertx from 4.2.6 to 4.3.1.
Upgrade pac4j from 5.3.1 to 5.4.3.
Remove pinned versions of indirect dependencies - the direct dependenies
come with indirecty versions that contain the security fixes.
Upgrade test dependencies.
Small code changes are required by the new dependency versions.

MODLOGSAML-142: Upgrade dependencies: RMB 34, Vert.x 4.3.1, pac4j 5.4.3

---

pom.xml

https://nvd.nist.gov/vuln/detail/CVE-2022-22970
In spring framework versions prior to 5.3.20+ , 5.2.22+ and old unsupported versions, applications that handle file uploads are vulnerable to DoS attack if they rely on data binding to set a MultipartFile or javax.servlet.Part to a field in a model object.
org.pac4j:pac4j-saml@5.4.3 comes with the depenceny org.springframework:spring-beans@5.3.19 and there is no released pac4j-saml version with a fix.
Therefore we need to bump the springframework version. Run
```
mvn dependency:tree -Dincludes=org.springframework
```
to check that the upgrade has correctly been applied:
```
[INFO] org.folio:mod-login-saml:jar:2.5.0-SNAPSHOT
[INFO] \- org.pac4j:pac4j-saml:jar:5.4.3:compile
[INFO]    +- org.springframework:spring-beans:jar:5.3.21:compile …
```

MODLOGSAML-144: spring framework 5.3.21 fixing DoS (CVE-2022-22970)

---

src/main/java/org/folio/rest/impl/ApiInitializer.java
src/main/java/org/folio/rest/impl/SamlAPI.java

Some IdPs send a big XML in the SAMLResponse form attribute when calling POST /saml/callback.
This exceeds Vert.x' default maximum of 8192 bytes.
https://samltest.id/ has about 14400 bytes, UChicago has reported "roughly 64K" in RMB-856.

MODLOGSAML-148: Bump maxFormAttributeSize from 8192 to 65536

---

src/main/java/org/folio/rest/impl/SamlAPI.java
src/test/java/org/folio/rest/impl/SamlAPITest.java

The exception `java.lang.String cannot be cast to class java.util.List` is most likely thrown in this code:
(List<?>) credentials.getUserProfile().getAttribute(samlAttributeName)
I propose this change:
getList(credentials.getUserProfile().getAttribute(samlAttributeName))
and
private static List<?> getList(Object o) {
if (o == null) {
return Collections.emptyList();
}
if (o instanceof List) {
return (List<?>) o;
}
return List.of(o);
}
This wraps the attribute into a list if it isn't a List.
All other code changes are needed for testability.

MODLOGSAML-140: Wrap samlAttributeName String in List

---

src/test/java/org/folio/util/DumpUtilTest.java

Use JDK 17 and run "mvn clean install".
Build fails with this error:
```
java.lang.reflect.InaccessibleObjectException: Unable to make field private static final jdk.internal.misc.Unsafe java.util.concurrent.atomic.AtomicInteger.U accessible: module java.base does not "opens java.util.concurrent.atomic" to unnamed module @62bd2070
at org.folio.util.DumpUtilTest.dumpContent(DumpUtilTest.java:26)
```
This is caused by the strong encapsulation of the Java Platform Module System.
Fixing it is easy because it is in the unit test only, not in the production code.

MODLOGSAML-151: JDK 17 - InaccessibleObjectException AtomicInteger

---

.github/workflows/api-doc.yml
.github/workflows/api-lint.yml
.github/workflows/api-schema-lint.yml
Jenkinsfile
ramls/saml-login.raml

[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).

FOLIO-3678 MODLOGSAML-160 Use GitHub Workflows api-lint and api-schema-lint and api-doc

---

src/main/java/org/folio/config/SamlClientLoader.java
src/test/java/org/folio/rest/impl/IdpTest.java
src/test/resources/mock_idptest_post.json
src/test/resources/mock_idptest_post_legacy.json
src/test/resources/mock_idptest_redirect.json
src/test/resources/mock_idptest_redirect_legacy.json

Now that RTR won't be the default in stripes it doesn't make sense to make callback-with-expiry the default in this module. When stripes makes RTR the default, we should change this back then.
Having this get into Poppy will make it easier to test for Poppy as well since we no longer need to make the tedious configuration.
There is now a ticket in stripes to make manual configuration unnecessary in Q. That's here: https://issues.folio.org/browse/UITEN-272

MODLOGSAML-180: Changes callback to be default rather than callback-with-expiry

---

README.md

The result of 
https://folio-org.atlassian.net/browse/MODLOGSAML-111
was that the configuration values were not longer stored in mod-configuration.
Instead mod-login-saml "stores its configuration values itself" see 
https://github.com/folio-org/rfcs/blob/master/text/0006-folio-distributed-vs-centralized-configration.md#distributed-configuration-is-preferred
.
The README is corrected in regard to the storage of the configuration values.

Remove Reference of mod-configuration in README.md
